### PR TITLE
chore(*): hyper update + cleanup

### PR DESCRIPTION
**Pull request by Ryman**

### CODE REVIEW

**Comment by Ryman** [comment]
@cybergeek94 I had a local branch fixing those nightly errors (and adding a test for the ssl feature), and realised you'd missed a branch for the ssl implementation on `Server` when checking it again. I'll merge your changes in this PR after I've tweaked the travis config.

**Comment by Ryman** [comment]
@cburgdorf @SimonPersson The CI change slows Travis down a bit (since it doubles the number of individual builds) but I'd prefer to have the combinations tested for now and we can refine it in future (perhaps by letting [cargo manage a build matrix](https://github.com/rust-lang/cargo/issues/1173#issuecomment-105545365)) if it becomes a real issue.

r?

**Comment by Ryman** [comment]
:zap: friendly ping @SimonPersson @cburgdorf  :zap:

**Comment by SimonPersson** [comment]
Looks good to me! :)

[image: :zap:] friendly ping @SimonPersson <https://github.com/SimonPersson>
@cburgdorf <https://github.com/cburgdorf> [image: :zap:]

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/nickel-org/nickel.rs/pull/321#issuecomment-203108032>

**Comment by Ryman** [comment]
@homu r+

**Pull request merged**
