### PR TITLE
feat(response): add next_middleware method for convenience

### PR DESCRIPTION
**Pull request by Ryman**
This seems more intuitive, less imports, less types to know about, does what it says.

### CODE REVIEW

**Comment by cburgdorf** [comment]
For ergonomics we could add the same for this, right?

```rust
let stream = try!(res.start());
Ok(Halt(stream))
```

**Comment by Ryman** [comment]
Currently `res.send("")`?

**Comment by cburgdorf** [comment]
True, but it's kind of unintuitive ;) I think having `res.halt_middleware()` feels more aligned with `res.next_middleware()`

**Comment by Ryman** [comment]
I actually feel like we should change `res.end()` as it's not really needed anymore in it's current form (hyper now handles dropping the response properly)

**Comment by Ryman** [comment]
@cburgdorf @SimonPersson Rebased, anyone want to r+? I think the `halt` discussion can go in a new thread?

**Comment by SimonPersson** [comment]
Sure! Fix that one empty line and you can feel free to r+ yourself :+1:

**Comment by Ryman** [comment]
@homu r=SimonPersson

**Pull request merged**
