### PR TITLE
fix(Makefile): update to cargo usage

### LINKED ISSUE #144: make doc fails
With nightly:

```shell
$ make doc
...
rustdoc -L target/deps src/lib.rs
src/lib.rs:27:1: 27:18 error: multiple matching crates for `log`
src/lib.rs:27 extern crate log;
              ^~~~~~~~~~~~~~~~~
note: candidates:
note: path: /usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-4e7c5e5c.so
note: path: /usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-4e7c5e5c.rlib
note: crate name: log
note: path: /home/rgs/src/rust/nickel.rs/target/deps/liblog-6ccd07f1f8244a62.rlib
note: crate name: log
src/lib.rs:27:1: 27:18 error: can't find crate for `log`
src/lib.rs:27 extern crate log;
              ^~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
thread '<unnamed>' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:151
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "rustc failed"', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:743
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:362
Makefile:14: recipe for target 'doc' failed
make: *** [doc] Error 101
```

Ideas?

### PR DESCRIPTION
**Pull request by Ryman**
Should fix #144.

cc @rgs1

### CODE REVIEW

**Comment by Ryman** [comment]
An alternative to this is to just drop the Makefile in favor of users knowing how to cargo?

**Comment by SimonPersson** [comment]
I prefer to drop the Makefile. It doesn't really fill any purpose any more as far as I can see.

**Comment by Ryman** [comment]
@SimonPersson agree, I removed it and updated the readme instead, please merge if you don't spot anything additional to update.

**Comment by SimonPersson** [comment]
Looks good, merged.

**Comment by rgs1** [comment]
update_online_docs.sh still has:

```shell
make doc
```

**Pull request merged**
