### PR TITLE
fix(serverdata): extend lifetime of return value of {Request|Response}::server_data

### PR DESCRIPTION
**Pull request by Ryman**
This is much more flexible!

### CODE REVIEW

**Comment by Ryman** [comment]
@cburgdorf @SimonPersson  This also highlights an oversight from when we merged the serverdata branch, for `Response`, both `data` and `server_data` were implemented! (I plan to remove `data` on next minor version bump)

**Comment by Ryman** [comment]
@homu r+

**Comment by cburgdorf** [comment]
What's the effect of this in practice? (just trying to understand and learn)

**Comment by Ryman** [comment]
Previously:
```rust 
let foo = response.server_data();
let bar = foo.bar(); // something derived from foo (a reference, not owned data)
return response.send(bar) // error: response is currently borrowed
```
Would fail as `server_data`'s lifetime was borrowing the `Response` (via lifetime elision). i.e. the signature was actually `fn server_data<'a>(&'a self) -> &'a Data`.

This change, links the lifetime to something which outlives the `Response`, so by the function signature (non-elided) `fn server_data<'a>(&'a self) -> &'mw Data`, it's not tying the lifetime of the call (`'a`) to `server_data`. 

This means we're able to continue using the response  and are free to mutate and move it, while `server_data` is guaranteed to live as long as the lifetime `'mw` is valid (which is a lot longer than what it was before, which was linked to that specific function call).

**Comment by cburgdorf** [comment]
Gotcha! Thank you for the insights. Greetings from Thailand btw ;)
Am 02.11.2015 05:52 schrieb "Ryman" <notifications@github.com>:

**Pull request merged**
