### PR TITLE
WIP: Hyper 11

### PR DESCRIPTION
**Pull request by nacardin**
Most examples are working and tests are mostly passing on stable-2017-07-20.

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were style issues with your Pull Request:

 * Commit: ac36432cff21e241e7536125cfbd7c5dfb255bbf
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/nickel-org/nickel.rs/blob/master/contributing.md

---
This message was auto-generated by https://gitcop.com

**Comment by mpkh** [comment]
Hello, do you know if they returned ssl support? plan to get it back?

**Comment by jolhoeft** [comment]
We're tracking the SSL support in #415. The short answer is hyper no longer has native ssl support. I currently use apache to redirect ssl https to a localhost only port nickel is listening on. We intend to support ssl in the long run, but the current focus is getting hyper 0.11 support done, which is proving more of a challenge than I'd expected.

**Comment by jolhoeft** [comment]
Closing in favor of #459, which has been merged

**Pull request closed without merging**
