### PR TITLE
Markdown typo README.md

### PR DESCRIPTION
**Pull request by Biacode**
Fixed markdown typo

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were style issues with your Pull Request:

 * Commit: cda0c65d77c347beaa36a4b987ecf01ad64e5113
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/nickel-org/nickel.rs/blob/master/contributing.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were style issues with your Pull Request:

 * Commit: cda0c65d77c347beaa36a4b987ecf01ad64e5113
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4d82fb090c03c8364ff795c79ca18159998c4ce8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/nickel-org/nickel.rs/blob/master/contributing.md

---
This message was auto-generated by https://gitcop.com

**Comment by Biacode** [comment]
I've noticed that there is other pull request for markdown typo #397 please close this one!

**Comment by jolhoeft** [comment]
Changes merged manually as pull request #408

**Pull request closed without merging**
