### PR TITLE
chore(*): Upgrade Several Crates

### PR DESCRIPTION
**Pull request by jolhoeft**
Addresses #395

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were style issues with your Pull Request:

 * Commit: 2d64d31fd6f214a884bc5729f3da3d58b196320f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7eff6bc05f24cd23cf163a974a9aeb53c202ebf1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/nickel-org/nickel.rs/blob/master/contributing.md

---
This message was auto-generated by https://gitcop.com

**Comment by jolhoeft** [comment]
The Travis failures appear to be due to #399

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were style issues with your Pull Request:

 * Commit: 2d64d31fd6f214a884bc5729f3da3d58b196320f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7eff6bc05f24cd23cf163a974a9aeb53c202ebf1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b517381648b6170b5bcf3f20e6d6e46ddc3c8532
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/nickel-org/nickel.rs/blob/master/contributing.md

---
This message was auto-generated by https://gitcop.com

**Comment by jolhoeft** [comment]
I've created a new pull request that is a bit cleaner, #401. Closing this in favor of that one.

**Pull request closed without merging**
