### PR TITLE
fix(*): FromStr now returns a Result, not an Option.

### PR DESCRIPTION
**Pull request by SimonPersson**
Fix for nightly.

### CODE REVIEW

**Comment by Ryman** [comment]
Failure in an example on travis

**Comment by SimonPersson** [comment]
Oops. Oh well, it compiles now but freezes in one test. I'm not sure why yet.

**Comment by SimonPersson** [comment]
@Ryman: Travis says all is well now.

**Comment by SimonPersson** [comment]
@Ryman - Changed the error type to `&'static str`.

**Pull request merged**
